version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - db-back

  app:
    restart: always
    build: ./app
    command: python main.py
    ports:
      - "5001:5001"
    env_file: .env
    depends_on:
      - db
    networks:
      - db-back

networks:
  db-back:

volumes:
  data:
